import { IntegrationError } from "@green-api/greenapi-integration";

export const ErrorCode = {
	KEY_INVALID: "KEY_INVALID",
	AUTOMATION_KEY_INVALID: "AUTOMATION_KEY_INVALID",
	AUTOMATION_KEY_NOT_FOUND: "AUTOMATION_KEY_NOT_FOUND",
	INSTANCE_NOT_FOUND: "INSTANCE_NOT_FOUND",
	INSTANCE_ALREADY_CONNECTED: "INSTANCE_ALREADY_CONNECTED",
	INSTANCE_CREDENTIALS_INVALID: "INSTANCE_CREDENTIALS_INVALID",
	INSTANCE_NOT_AUTHORIZED: "INSTANCE_NOT_AUTHORIZED",
	INSTANCE_SETTINGS_UNAVAILABLE: "INSTANCE_SETTINGS_UNAVAILABLE",
	MESSENGER_UNSUPPORTED: "MESSENGER_UNSUPPORTED",
	JOB_NOT_FOUND: "JOB_NOT_FOUND",
	JOB_NOT_CANCELLABLE: "JOB_NOT_CANCELLABLE",
	JOB_CANCELLED: "JOB_CANCELLED",
	PHONE_INVALID: "PHONE_INVALID",
	RECIPIENT_NOT_FOUND: "RECIPIENT_NOT_FOUND",
	FILE_URL_EXPIRED: "FILE_URL_EXPIRED",
	FILE_URL_INVALID: "FILE_URL_INVALID",
	VALIDATION_FAILED: "VALIDATION_FAILED",
	OAUTH_STATE_INVALID: "OAUTH_STATE_INVALID",
	OAUTH_EXCHANGE_FAILED: "OAUTH_EXCHANGE_FAILED",
	AIRTABLE_NOT_CONNECTED: "AIRTABLE_NOT_CONNECTED",
	AIRTABLE_BASE_FORBIDDEN: "AIRTABLE_BASE_FORBIDDEN",
	AIRTABLE_TOKEN_EXPIRED: "AIRTABLE_TOKEN_EXPIRED",
	AIRTABLE_API_ERROR: "AIRTABLE_API_ERROR",
	AIRTABLE_RATE_LIMITED: "AIRTABLE_RATE_LIMITED",
	INBOUND_NOT_CONFIGURED: "INBOUND_NOT_CONFIGURED",
	INBOUND_DELIVERY_FAILED: "INBOUND_DELIVERY_FAILED",
	QR_UNAVAILABLE: "QR_UNAVAILABLE",
	GREEN_API_RATE_LIMITED: "GREEN_API_RATE_LIMITED",
	GREEN_API_ERROR: "GREEN_API_ERROR",
	WEBHOOK_SETTINGS_FAILED: "WEBHOOK_SETTINGS_FAILED",
	USER_NOT_MEMBER: "USER_NOT_MEMBER",
	USER_NOT_ADMIN: "USER_NOT_ADMIN",
	USER_NOT_FOUND: "USER_NOT_FOUND",
	INSTANCE_NOT_ASSIGNED: "INSTANCE_NOT_ASSIGNED",
	INSTANCE_FORBIDDEN: "INSTANCE_FORBIDDEN",
	NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
} as const;

export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];

export function apiError(code: ErrorCode, message: string, statusCode: number, details?: unknown): IntegrationError {
	return new IntegrationError(message, code, statusCode, details);
}
